const cardArray = [
  {
    id: 1,
    title: 'Первый товар',
    price: '170 ₽',
    address: 'Казань, р-н Вахитовский',
    time: '10 июля 11:39',
    img: '/images/card-image.jpg',
    desc: 'Продаю не спеша самокат в хорошем состоянии.',
  },
  {
    id: 2,
    title: 'Второй товар',
    price: '171 ₽',
    address: 'Казань, р-н Вахитовский',
    time: '10 июля 11:39',
    img: '/images/card-image.jpg',
    desc: 'Продаю не спеша самокат в хорошем состоянии.',
  },
  {
    id: 3,
    title: 'Третий товар',
    price: '172 ₽',
    address: 'Казань, р-н Вахитовский',
    time: '10 июля 11:39',
    img: '/images/card-image.jpg',
    desc: 'Продаю не спеша самокат в хорошем состоянии.',
  },
  {
    id: 4,
    title: 'Четвертый товар',
    price: '173 ₽',
    address: 'Казань, р-н Вахитовский',
    time: '10 июля 11:39',
    img: '/images/card-image.jpg',
    desc: 'Продаю не спеша самокат в хорошем состоянии.',
  },
  {
    id: 5,
    title: 'Пятый товар',
    price: '174 ₽',
    address: 'Казань, р-н Вахитовский',
    time: '10 июля 11:39',
    img: '/images/card-image.jpg',
    desc: 'Продаю не спеша самокат в хорошем состоянии.',
  },
  {
    id: 6,
    title: 'Шестой товар',
    price: '175 ₽',
    address: 'Казань, р-н Вахитовский',
    time: '10 июля 11:39',
    img: '/images/card-image.jpg',
    desc: 'Продаю не спеша самокат в хорошем состоянии.',
  },
]

export default cardArray